
import React from 'react';
import { Shipment } from '../types';

interface TrackingLabelProps {
  shipment: Shipment;
}

export const TrackingLabel: React.FC<TrackingLabelProps> = ({ shipment }) => {
  // Using Google Charts API for QR code generation as it's a reliable, no-dependency way to get a scannable code
  const qrUrl = `https://chart.googleapis.com/chart?chs=200x200&cht=qr&chl=${shipment.trackingNo}&choe=UTF-8`;

  return (
    <div id="print-label" className="print-label-container bg-white p-4 border-2 border-black w-[4in] h-[6in] flex flex-col font-sans text-black mx-auto overflow-hidden">
      <style>{`
        @media print {
          body * { visibility: hidden; }
          #print-label, #print-label * { visibility: visible; }
          #print-label {
            position: absolute;
            left: 0;
            top: 0;
            width: 4in;
            height: 6in;
            padding: 20px;
            border: 2px solid black;
          }
          @page { size: 4in 6in; margin: 0; }
        }
      `}</style>
      
      {/* Header Section */}
      <div className="border-b-2 border-black pb-2 mb-2 flex justify-between items-start">
        <div>
          <h1 className="text-xl font-black uppercase tracking-tighter">SinoTan Logistics</h1>
          <p className="text-[10px] font-bold">China-Tanzania Express Service</p>
        </div>
        <div className="text-right">
          <p className="text-[12px] font-bold">{shipment.createdAt}</p>
          <div className="text-[16px] font-black border-2 border-black px-2 mt-1 inline-block">
            {shipment.originRegion} → {shipment.destinationRegion}
          </div>
        </div>
      </div>

      {/* Main Barcode/ID Section */}
      <div className="flex-1 flex flex-col items-center justify-center py-4 border-b-2 border-black">
        <h2 className="text-4xl font-black mb-4 font-mono tracking-widest">{shipment.trackingNo}</h2>
        <img 
          src={qrUrl} 
          alt="Tracking QR Code" 
          className="w-48 h-48 border-2 border-black p-2 bg-white"
        />
        <p className="mt-2 text-[8px] uppercase font-bold text-gray-500 italic">Scan code for shipment details & manifest</p>
      </div>

      {/* Consignee Section */}
      <div className="pt-4 space-y-2">
        <div>
          <p className="text-[10px] font-black uppercase bg-black text-white px-2 inline-block mb-1">Receiver (Consignee)</p>
          <p className="text-[18px] font-black leading-tight">{shipment.customerName || 'N/A'}</p>
          <p className="text-[14px] font-bold font-mono">{shipment.customerPhone || 'N/A'}</p>
        </div>
        
        <div className="pt-2 border-t border-black/10">
          <p className="text-[10px] font-black uppercase mb-1 text-gray-600 tracking-widest">Delivery Destination</p>
          <p className="text-[12px] font-bold uppercase leading-tight">
            {shipment.destinationRegion === 'TZ' ? 'Dar es Salaam Port WH (DAR-P01)' : 'Guangzhou Main WH (GZ-M01)'}
          </p>
          <p className="text-[10px] text-gray-500 font-bold mt-1">Total Packages: {shipment.packageCount || 1}</p>
        </div>
      </div>

      {/* Bottom Legal/Security */}
      <div className="mt-auto pt-2 border-t-2 border-black flex justify-between text-[8px] font-bold uppercase">
        <span>Waybill Generated by ST Hub System</span>
        <span>Audit: {Math.random().toString(36).substr(2, 6).toUpperCase()}</span>
      </div>
    </div>
  );
};
